[tool.poetry]
name = "flet-demo"
version = "0.1.0"
description = ""
authors = ["varshithvvs <sai_varshith@epam.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
flet = "^0.24.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
